# -*- coding: utf-8 -*-
"""tugas1 _Pegantar_SainsData_Faqih.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lo0_Os1nM3FDes_PzC77t_LlvM4DUhC

# Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

"""# Data Loading"""

# membaca file csv
df = pd.read_csv("/content/Tugas 1 STDA4101-2024.1 (1).csv", delimiter=';')
df

"""# Data Wrangling"""

df.head()

# memeriksa kolom yang NaN
df.isna().sum()

# menghapus kolom yang berisikan NaN
df = df.drop(columns=["Unnamed: 1", "Unnamed: 2"], errors='ignore')
df.head()

"""# Exploratory Data Analysis

Melakukan analisis statistik deskriptif:
1. Ukuran pemusatan data: Mean, Median, dan Mode
2. Ukuran penyebaran data: Range, Variance, dan Standard Deviation
3. Bentuk distribusi data: Symmetry, Skewness, dan Kurtosis.
4. Buatlah visualisasi data univariat menggunakan Quartile Plot (box plot) dan berikan ulasan
Anda tentang plot tersebut.
"""

# Soal 1. menghitung nilai mean, median, dan modus untuk kolom 'AGE'
mean_age = df['AGE'].mean()
median_age = df['AGE'].median()
mode_age = df['AGE'].mode()

print("Mean Age:", mean_age)
print("Median Age:", median_age)
print("Mode Age:", mode_age)

# Soal 2. Menghitung Range, Variance, dan Standard Deviation
range_age = df['AGE'].max() - df['AGE'].min()
variance_age = df['AGE'].var()
std_dev_age = df['AGE'].std()

print("Range Age:", range_age)
print("Variance Age:", variance_age)
print("Standard Deviation Age:", std_dev_age)

# Soal 3. Menampilkan Bentuk distribusi data: SSkewness, dan Kurtosis
skewness = stats.skew(df['AGE'])
kurtosis = stats.kurtosis(df['AGE'])

print("Skewness:", skewness)
print("Kurtosis:", kurtosis)

#soal 4. Buatlah visualisasi data univariat menggunakan Quartile Plot (box plot) dan berikan ulasannya tentang plot tersebut.
# Plot menggunakan boxplot

plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='AGE')
plt.title('Box Plot of Age')
plt.xlabel('Age')
plt.show()

"""# Insight

Pusat Datanya:

Kotak tengah (interquartile range) menunjukkan rentang antara kuartil pertama (Q1) dan kuartil ketiga (Q3), sedangkan garis horizontal di dalam kotak menunjukkan median. Ini memberikan informasi tentang nilai tengah dari data "AGE" mediannya 47,5.

Rentang Interkuartil:

Panjang kotak menunjukkan seberapa jauh data tersebar di antara Q1 dan Q3. Rentang yang lebih panjang menunjukkan variabilitas yang lebih besar dalam data.

Outliers atau pencilan dari data AGE:

Titik di luar whiskers (garis vertikal yang menjulang dari kotak) menunjukkan outliers, yaitu nilai-nilai 18 kebawah dan 75 keatas.

Simetri dan Skewness:

Posisi median dalam kotak dan panjang whiskers memberikan indikasi tentang simetri distribusi. Jika median lebih dekat ke Q1, distribusi mungkin miring ke kanan (skewed right). Jika median lebih dekat ke Q3, distribusi mungkin miring ke kiri (skewed left).

jadi data pada kolom "AGE"data tersebut cenderung miring ke kanan (skewed right) atau memiliki tail yang lebih panjang di sisi kanan sekian terima kasih apabila ada kesalahan dalam penyampaian presentasi boxplot mohon dikoreksi
"""